# Production environment configuration
email.imap.host=imap.prodserver.com
email.imap.port=993
email.imap.user=produser@company.com
email.imap.password=prodpassword
attachment.save.dir=/mnt/prod/attachments
attachment.storage.type=sapdms
