# Development environment configuration
email.imap.host=imap.devserver.com
email.imap.port=993
email.imap.user=devuser@company.com
email.imap.password=devpassword
attachment.save.dir=excel/dev
attachment.storage.type=local
